# Generated by Django 5.2.3 on 2025-07-31 17:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('translation', models.CharField(default='kjv', max_length=20)),
                ('book', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShownVerse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_shown', models.DateField(default=django.utils.timezone.now)),
                ('translation', models.CharField(default='kjv', max_length=20)),
                ('book', models.CharField(blank=True, max_length=50, null=True)),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daily_verse_app.verse')),
            ],
            options={
                'unique_together': {('date_shown', 'translation', 'book')},
            },
        ),
    ]
